from scripts.full_pipeline.sp500_forecast_multivariate_2_weeks import main_sp500_forecast_multivariate_2_weeks

# generate predictions
future_forecast_2_weeks = main_sp500_forecast_multivariate_2_weeks()
